print("string formatting")
name = input("enter your name: ")
age = int(input("enter your age: "))
print("old method")
print("hello " + name + " you are " + str(age) + " years old")
print("python3")
print("hello {} you are {} years old".format(name, age + 2))
print("python3.6")
print(f"hello {name} you are {age + 4} years old")